[build]
  base = "Frontend"
  publish = "Frontend/dist"
  command = "cd Frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "https://e-learning-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_API_BASE_URL = "https://e-learning-backend.onrender.com/api" }

[context.deploy-preview]
  environment = { VITE_API_BASE_URL = "https://e-learning-backend.onrender.com/api" }

[context.branch-deploy]
  environment = { VITE_API_BASE_URL = "https://e-learning-backend.onrender.com/api" }
