[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.install]
cmds = ["cd Backend/Dev-learning-Platform && mvn clean package -DskipTests"]

[phases.build]
cmds = ["cd Backend/Dev-learning-Platform && mvn clean package -DskipTests"]

[start]
cmd = "cd Backend/Dev-learning-Platform && java -jar target/Dev_learning_Platform-0.0.1-SNAPSHOT.jar"
