# Railway Configuration for E-Learning Platform v2.0
[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/Dev_learning_Platform-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PORT = "8080" }

[environments.production.services.database]
type = "postgresql"
