name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: |
        cd Backend/Dev-learning-Platform
        ./mvnw test -Dspring.profiles.active=dev
    
    - name: Deploy to OCI VM
      if: success()
     uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        timeout: 300s
        command_timeout: 120s
        script: |
          set -e
          
          echo "=== Iniciando deployment ==="
          cd /home/opc/Git-Repository/E-Learning-Platform/Backend/Dev-learning-Platform
          
          echo "=== Verificando Java ==="
          java -version
          
          echo "=== Haciendo git pull ==="
          git pull origin main
          
          echo "=== Ejecutando tests en producción ==="
          ./mvnw test -Dspring.profiles.active=prod
          
          if [ $? -eq 0 ]; then
            echo "=== Tests exitosos, construyendo aplicación ==="
            ./mvnw clean package -Dspring.profiles.active=prod -DskipTests
            
            echo "=== Deteniendo servicio anterior ==="
            sudo systemctl stop elearning-backend || echo "Servicio no estaba corriendo"
            
            echo "=== Iniciando nuevo servicio ==="
            sudo systemctl start elearning-backend
            
            echo "=== Esperando que el servicio inicie ==="
            sleep 10
            
            echo "=== Verificando estado del servicio ==="
            # Esperar un poco más para que systemd tenga tiempo de intentar el start
            sleep 5
            
            if sudo systemctl is-active --quiet elearning-backend; then
              echo "✅ Despliegue exitoso - Servicio activo"
              sudo systemctl status elearning-backend --no-pager -l
              
              # Health check opcional
              echo "=== Verificando health endpoint ==="
              sleep 10
              curl -f http://localhost:8080/actuator/health || echo "Health check no disponible"
              
            else
              echo "❌ Error: El servicio no se inició correctamente"
              echo "=== Estado detallado del servicio ==="
              sudo systemctl status elearning-backend --no-pager -l
              
              echo "=== Últimos 50 logs del servicio ==="
              sudo journalctl -u elearning-backend --no-pager -l -n 50
              
              echo "=== Verificando si el JAR existe ==="
              ls -la target/Dev-learning-Platform-0.0.1-SNAPSHOT.jar
              
              echo "=== Verificando permisos ==="
              ls -la target/
              
              echo "=== Verificando Java ==="
              java -version
              which java
              
              echo "=== Intentando ejecutar JAR manualmente para debugging ==="
              timeout 30s java -jar target/Dev-learning-Platform-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod || echo "Ejecución manual falló"
              
              exit 1
            fi
            
          else
            echo "❌ Error en los tests, no se despliega"
            exit 1
          fi
          
          echo "=== Deployment completado exitosamente ==="