name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run Tests
      env:
        JWT_SECRET_KEY: testSecretKeyForCITestingPurposesOnly123456789
        JWT_EXPIRATION_TIME: 86400000
        STRIPE_API_KEY: test_stripe_key
        STRIPE_API_PUBLIC_KEY: test_stripe_public_key
        STRIPE_WEBHOOK_SECRET: test_stripe_webhook_secret
      run: |
        cd Backend/Dev-learning-Platform
        ./mvnw clean test -Dspring.profiles.active=test -q -Dlogging.level.org.springframework.boot.autoconfigure=OFF
    
    - name: Deploy to OCI VM
      if: success()
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        timeout: 300s
        command_timeout: 120s
        script: |
          set -e
          
          echo "=== Iniciando deployment ==="
          cd /home/opc/Git-Repository/E-Learning-Platform/Backend/Dev-learning-Platform
          
          echo "=== Haciendo git pull ==="
          git switch main
          git pull origin main
          
          echo "=== Ejecutando tests en producción ==="
          ./mvnw test -Dspring.profiles.active=prod -q
          
          if [ $? -eq 0 ]; then
            echo "=== Tests exitosos, deteniendo servicio para construcción ==="
            sudo systemctl stop elearning-backend

            echo "=== Construyendo aplicación ==="
            mvn clean package -Pprod -DskipTests

            echo "=== Reiniciando daemon ==="
            sudo systemctl daemon-reload

            echo "=== Iniciando servicio ==="
            sudo systemctl start elearning-backend

            echo "=== Verificando despliegue ==="
            sleep 15

            max_attempts=20
            attempt=1
            until curl -sf http://localhost:8080/actuator/health; do
              echo "Intento $attempt/$max_attempts: Backend aún no disponible..."
              attempt=$((attempt+1))
              if [ $attempt -gt $max_attempts ]; then
                echo "❌ Backend no respondió al health check después de $max_attempts intentos."
                sudo journalctl -u elearning-backend --no-pager -l -n 20
                exit 1
              fi
              sleep 5
            done
            echo "✅ Despliegue exitoso y health check OK"
            
            if sudo systemctl is-active --quiet elearning-backend; then
              echo "✅ Despliegue exitoso"
              curl -f http://localhost:8080/actuator/health || echo "Health check no disponible"
            else
              echo "❌ Error en el despliegue"
              sudo journalctl -u elearning-backend --no-pager -l -n 20
              exit 1
            fi
          else
            echo "❌ Error en los tests"
            exit 1
          fi