name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd Backend/Dev-learning-Platform
        ./mvnw test -Dspring.profiles.active=dev

    - name: Deploy to OCI VM
      if: success() # Solo si los pasos anteriores fueron exitosos
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /home/opc/Git-Repository/E-Learning-Platform/Backend/Dev-learning-Platform
          git pull origin main
          ./mvnw test -Dspring.profiles.active=prod
          if [ $? -eq 0 ]; then
            ./mvnw clean package -Dspring.profiles.active=prod
            # Detener proceso anterior
            pkill -f 'java -jar'
            sleep 5
            # Iniciar el backend en segundo plano
            nohup java -jar target/Dev-learning-Platform-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
            sleep 10
            if ! pgrep -f 'java -jar'; then
              echo "El backend no se inició correctamente"
              exit 1
            fi
            echo "Despliegue exitoso"
            exit 0
          fi