name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run Tests
      run: |
        cd Backend/Dev-learning-Platform
        ./mvnw clean test -Dspring.profiles.active=test -q
    
    - name: Deploy to OCI VM
      if: success()
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        timeout: 300s
        command_timeout: 120s
        script: |
          set -e
          
          echo "=== Iniciando deployment ==="
          cd /home/opc/Git-Repository/E-Learning-Platform/Backend/Dev-learning-Platform
          
          echo "=== Haciendo git pull ==="
          git pull origin main
          
          echo "=== Ejecutando tests en producción ==="
          ./mvnw test -Dspring.profiles.active=prod -q
          
          if [ $? -eq 0 ]; then
            echo "=== Tests exitosos, construyendo aplicación ==="
            ./mvnw clean package -Dspring.profiles.active=prod -DskipTests -q
            
            echo "=== Reiniciando servicio ==="
            sudo systemctl restart elearning-backend
            
            echo "=== Verificando despliegue ==="
            sleep 15
            
            if sudo systemctl is-active --quiet elearning-backend; then
              echo "✅ Despliegue exitoso"
              curl -f http://localhost:8080/actuator/health || echo "Health check no disponible"
            else
              echo "❌ Error en el despliegue"
              sudo journalctl -u elearning-backend --no-pager -l -n 20
              exit 1
            fi
          else
            echo "❌ Error en los tests"
            exit 1
          fi